### ISSUE TITLE
Web based login

### ISSUE THREAD

**Issue by pajlada** [pajlada/tyggbot#28]
Should be admin only to begin with.
Use twitch authentication.
Can be used to modify highlights, see all available filters/banphrases etc.
"admin only" means people with level 500+

**Comment by pajlada** [comment]
Fixed today.
In the footer, there's a Login and Admin zone link.
In the admin zone, you can access banphrases, banned links etc.

**Comment by hptk** [comment]
The link to "Admin Zone" is still visible for users without admin rights, resulting in a 403 when clicked. The best would be to just not show the link, right? That, or something else than 403 on the other side.

**Comment by pajlada** [comment]
@hptk sounds good, created a new issue for it #189
