### ISSUE TITLE
Installation instructions for the web part

### ISSUE THREAD

**Issue by pajlada** [pajlada/tyggbot#31]
To do this I should just get a fresh installation of ubuntu 14.0.4 and go from there.
This would help me add any files that are missing from the repository.

**Comment by Nacht123** [comment]
**This is what I have noticed, during the install of the Web interface.**
*Xubuntu 15.04 and nginx*

**MISSING FILES**

config *WIKI wrong*

pip install pip-requirements.txt *from tyggbot-web on github*
sudo pip3 install apscheduler   *;MISSED ?*

*from tyggbot-web on github missed*
static/src/ 
Gruntfile.js
package.json 
semantic.json 

**Change Config**
[web]
; Enter the domain where the site will reside. Example: tyggbot.pajlada.se
domain = 127.0.0.1:2325
; What optional modules should be enabled
; modules = linefarming

; Freely capitalized/spelled name of the streamer. Example: Pajen
streamer_name = StreamerName

[clr-overlay]
; TODO: enter description of widget_id here
widget_id = abcdefgh



**Change *Gruntfile.js* with your links**


**??????**
**Not sure but this worked for me. Maybe different order.**
**??????**

apt-get install nodejs
sudo ln -s "$(which nodejs)" /usr/bin/node

sudo npm install semantic-ui ?# not sure if needed installed nodejs after this.

sudo npm install -g gulp
sudo npm install .

**??????**


cd static
gulp build

run app.py

**Comment by Nacht123** [comment]
Fixed Keepo
https://github.com/pajlada/tyggbot/wiki/Installation-Bot
https://github.com/pajlada/tyggbot/wiki/Installation-Website

**Comment by pajlada** [comment]
Looks good, thanks!
