### ISSUE TITLE
Beautify URL's in tweets

### ISSUE THREAD

**Issue by wallrik** [pajlada/tyggbot#4]
When a tweet is posted there is no way to see what the link is, as only the **t.co** link link is shown.
It should be possible to beautify the text before it is sent to chat.

In [tyggbot.py#L118](https://github.com/pajlada/tyggbot/blob/41f5932f5f762b0d02cf2e5a0a16fd05bec4b6d0/tyggbot.py#L118) after `def on_status(self, tweet)` it should be possible to use `tweet.entities['urls']` to fetch `expanded_url` as shown in Twitter's API documentation:

[Entities in Objects - The urls entity](https://dev.twitter.com/overview/api/entities-in-twitter-objects#urls)
```javascript
{
  ...
  "text": "Today, Twitter is updating embedded Tweets to enable a richer photo experience: https:\/\/t.co\/XdXRudPXH5",
  "entities": {
    "hashtags": [],
    "symbols": [],
    "urls": [{
      "url": "https:\/\/t.co\/XdXRudPXH5",
      "expanded_url": "https:\/\/blog.twitter.com\/2013\/rich-photo-experience-now-in-embedded-tweets-3",
      "display_url": "blog.twitter.com\/2013\/rich-phot\u2026",
      "indices": [80, 103]
    }],
    "user_mentions": []
  }
}
```
How to do the actual replace, I don't know. I guess the code has to be able to handle more than one link per tweet, which means using the **url** key, and replace it with **expanded_url**. Because if there's more than one link, the **indices** key will not be accurate after the first link has been replaced.

Also, while beautifying the link, I personally would like to remove the http:// prefix to save some space in chat, just like Twitter does with their **display_url**. But since that key is cut off if the link is long, that one can probably not be used for chat.

**Comment by pajlada** [comment]
Fixed by @0rmi in #5
