### ISSUE TITLE
Banphrases only removeable over the ID not the phrase

### ISSUE THREAD

**Issue by gempir** [pajlada/tyggbot#40]
Banphrases should be removeable by simply saying !remove banphrase MingLee

Currently the id is the only way of removing a banphrase. Not sure if intended or bug.

**Comment by Nacht123** [comment]
The filter is written in lowercase at the database.
It works if you typ **!remove banphrase minglee**

**Comment by pajlada** [comment]
@gempir What @Nacht123 said.
I've fixed this in the following commit: 046548a1384adb21c83c162304ef203a9b706427
so you no longer need to lowercase your banphrase manually when you try to remove it.

I'll need to rethink banphrases at a later stage if there's a better way to solve case-sensitiveness.
