### ISSUE TITLE
!remove highlight command

### ISSUE THREAD

**Issue by Nacht123** [pajlada/tyggbot#41]
I was testing stuff with the bot and i noticed, 
there is no **command to remove accidentally added highlights** or just boring stuff.

I would prefer 
*level=500,*
*mod_only=False,*

to **avoid** that this will get abused by random 'mods', who are level 100 twitch mods.

**Comment by pajlada** [comment]
New command, level 500, mod_only=False sounds good.
!remove highlight <id>

**Comment by pajlada** [comment]
Fixed in 363687bed347fead51f3d56cdf71fc287829879c
