### ISSUE TITLE
duel winstreaks?

### ISSUE THREAD

**Issue by pajlada** [pajlada/tyggbot#58]
,for the winstreak: have the time of the last duel already on your page - just need to capture the result. if it's win winstreak += 1 else winstreak = 0 -> sort user's descending by winstreak count and you should get the list

do we want this?

**Comment by gigglearrows** [comment]
It does sound awesome. I support this

**Comment by hptk** [comment]
Well this should rarely get over 3, I mean 50% cahnce recursively is deminishing quickly. Maybe get winrates for each person and sort users by ESPORT PogChamp -rate (luck)

**Comment by pajlada** [comment]
Fixed
