### ISSUE TITLE
Some videos don't allow embedding, can we fix this? pleblist

### ISSUE THREAD

**Issue by pajlada** [pajlada/tyggbot#59]
Example video URL: https://www.youtube.com/watch?v=GKBh0kpspVI&feature=youtu.be

**Comment by hptk** [comment]
Thanks for the issue! I thought maybe you can access the video/sound files directly through the DASH Media Description Presentation (MPD) provided by youtube at the url http://www.youtube.com/get_video_info?video_id=GKBh0kpspVI, but it throws the same error as the website itself.

**Comment by ajtam** [comment]
hey, you can check if the video can be embedded by the youtube data api. When you make a request check the part->status->embeddable parameter (Boolean). Good luck. https://developers.google.com/youtube/v3/docs/videos/list

**Comment by pajlada** [comment]
Closing this issue as it seems there's no easy fix for it for now. Will reopen or recreate issue if there's a new development.
